#!/bin/bash

if [ $# -ne 2 ]; then
    echo "Usage: $0 <username> <password>"
    exit 1
fi

# function to cleanup the background processes
cleanup() {
    echo "Received termination signal, stopping jobs."
    kill $go_pid $ui_pid
    exit 1
}

# trap the SIGINT signal and call the cleanup function
trap cleanup SIGINT

user=$1
pass=$2

# run the Go app in the background
go mod download
go run app.go --username $user --password $pass &
go_pid=$!

# run the UI in the background
cd ui
./start_ui.sh &
ui_pid=$!

# wait for both background processes to finish
wait $go_pid
wait $ui_pid
